name: Clos de Tsampéhro
favicon: null
layout_spectrum: 0.43168616900220513
typography_spectrum: 0.21733159269206226
title: "Un Clos d'exception"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffffe'
    - '#0b0a09'
    - '#ba2e2a'
    - '#958f88'
    - '#52524e'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
