name: Tsampehro
favicon: null
layout_spectrum: 0.43168616900220513
typography_spectrum: 0.21733159269206226
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.595486223930493
  lightness: 0.46038863994181156
  saturation: 0.9627698238473386
  rhythmicContrast: 0.8437032748479396
purpose: []
